[tool.poetry]
name = "12-2"
version = "0.1.0"
description = ""
authors = ["Fedor Sazhin <fedorsazhin96@gmail.com>"]
readme = "README.md"
packages = [{include = "12"}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
